// Generated by lsc from node.ts

function isInsideRoot(resolvedRoot: string, resolvedPath: string, sep: string): bool
  requires (|sep| == 1)
{
  ((resolvedPath == resolvedRoot) || (|resolvedPath| >= |(resolvedRoot + sep)| && resolvedPath[..|(resolvedRoot + sep)|] == (resolvedRoot + sep)))
}

lemma isInsideRoot_ensures(resolvedRoot: string, resolvedPath: string, sep: string)
  requires (|sep| == 1)
  ensures ((isInsideRoot(resolvedRoot, resolvedPath, sep) == true) ==> ((resolvedPath == resolvedRoot) || (((|resolvedPath| > |resolvedRoot|) && (resolvedPath[0..|resolvedRoot|] == resolvedRoot)) && (resolvedPath[|resolvedRoot|..(|resolvedRoot| + 1)] == sep))))
{
}
